<?php
/**
 * AppTotalsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  WeFitter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * WeFitter API
 *
 * This is the WeFitter API
 *
 * OpenAPI spec version: v1.1
 * Contact: hello@wefitter.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace WeFitter\Client;

/**
 * AppTotalsTest Class Doc Comment
 *
 * @category    Class
 * @description AppTotals
 * @package     WeFitter\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AppTotalsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AppTotals"
     */
    public function testAppTotals()
    {
    }

    /**
     * Test attribute "total_calories"
     */
    public function testPropertyTotalCalories()
    {
    }

    /**
     * Test attribute "total_distance"
     */
    public function testPropertyTotalDistance()
    {
    }

    /**
     * Test attribute "total_steps"
     */
    public function testPropertyTotalSteps()
    {
    }

    /**
     * Test attribute "total_points"
     */
    public function testPropertyTotalPoints()
    {
    }
}
