<?php
/**
 * ProfileChallengeListTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  WeFitter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * WeFitter API
 *
 * This is the WeFitter API
 *
 * OpenAPI spec version: v1.1
 * Contact: hello@wefitter.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace WeFitter\Client;

/**
 * ProfileChallengeListTest Class Doc Comment
 *
 * @category    Class
 * @description ProfileChallengeList
 * @package     WeFitter\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProfileChallengeListTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProfileChallengeList"
     */
    public function testProfileChallengeList()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "public_id"
     */
    public function testPropertyPublicId()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "slogan"
     */
    public function testPropertySlogan()
    {
    }

    /**
     * Test attribute "start"
     */
    public function testPropertyStart()
    {
    }

    /**
     * Test attribute "end"
     */
    public function testPropertyEnd()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "goal"
     */
    public function testPropertyGoal()
    {
    }

    /**
     * Test attribute "goal_value"
     */
    public function testPropertyGoalValue()
    {
    }

    /**
     * Test attribute "goal_type"
     */
    public function testPropertyGoalType()
    {
    }

    /**
     * Test attribute "visibility"
     */
    public function testPropertyVisibility()
    {
    }

    /**
     * Test attribute "num_members"
     */
    public function testPropertyNumMembers()
    {
    }

    /**
     * Test attribute "leaderboard_rank"
     */
    public function testPropertyLeaderboardRank()
    {
    }

    /**
     * Test attribute "leaderboard_score"
     */
    public function testPropertyLeaderboardScore()
    {
    }

    /**
     * Test attribute "is_participating"
     */
    public function testPropertyIsParticipating()
    {
    }

    /**
     * Test attribute "repetition"
     */
    public function testPropertyRepetition()
    {
    }

    /**
     * Test attribute "avatar"
     */
    public function testPropertyAvatar()
    {
    }

    /**
     * Test attribute "data_source"
     */
    public function testPropertyDataSource()
    {
    }

    /**
     * Test attribute "activity_types"
     */
    public function testPropertyActivityTypes()
    {
    }
}
