<?php
/**
 * StressSummaryLinkedTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  WeFitter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * WeFitter API
 *
 * This is the WeFitter API
 *
 * OpenAPI spec version: v1.1
 * Contact: hello@wefitter.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace WeFitter\Client;

/**
 * StressSummaryLinkedTest Class Doc Comment
 *
 * @category    Class
 * @description StressSummaryLinked
 * @package     WeFitter\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StressSummaryLinkedTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StressSummaryLinked"
     */
    public function testStressSummaryLinked()
    {
    }

    /**
     * Test attribute "stress_qualifier"
     */
    public function testPropertyStressQualifier()
    {
    }

    /**
     * Test attribute "average_stress_level"
     */
    public function testPropertyAverageStressLevel()
    {
    }

    /**
     * Test attribute "max_stress_level"
     */
    public function testPropertyMaxStressLevel()
    {
    }
}
