<?php
/**
 * ChallengeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  WeFitter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * WeFitter API
 *
 * This is the WeFitter API
 *
 * OpenAPI spec version: v1.1
 * Contact: hello@wefitter.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace WeFitter\Client;

use WeFitter\Client\Configuration;
use WeFitter\Client\ApiException;
use WeFitter\Client\ObjectSerializer;

/**
 * ChallengeApiTest Class Doc Comment
 *
 * @category Class
 * @package  WeFitter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ChallengeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for challengeCreate
     *
     * Create challenge.
     *
     */
    public function testChallengeCreate()
    {
    }

    /**
     * Test case for challengeDelete
     *
     * Delete challenge.
     *
     */
    public function testChallengeDelete()
    {
    }

    /**
     * Test case for challengeLeaderboardHistoryRead
     *
     * Leaderboard history.
     *
     */
    public function testChallengeLeaderboardHistoryRead()
    {
    }

    /**
     * Test case for challengeLeaderboardRead
     *
     * Leaderboard.
     *
     */
    public function testChallengeLeaderboardRead()
    {
    }

    /**
     * Test case for challengeList
     *
     * List Challenges.
     *
     */
    public function testChallengeList()
    {
    }

    /**
     * Test case for challengeMemberCreate
     *
     * Add member.
     *
     */
    public function testChallengeMemberCreate()
    {
    }

    /**
     * Test case for challengeMemberDelete
     *
     * Remove member.
     *
     */
    public function testChallengeMemberDelete()
    {
    }

    /**
     * Test case for challengeMemberUpdate
     *
     * Add member.
     *
     */
    public function testChallengeMemberUpdate()
    {
    }

    /**
     * Test case for challengeMembersCreate
     *
     * Add members.
     *
     */
    public function testChallengeMembersCreate()
    {
    }

    /**
     * Test case for challengeMembersUpdate
     *
     * Add members.
     *
     */
    public function testChallengeMembersUpdate()
    {
    }

    /**
     * Test case for challengePartialUpdate
     *
     * Partial edit challenge.
     *
     */
    public function testChallengePartialUpdate()
    {
    }

    /**
     * Test case for challengePeriods
     *
     * Periods.
     *
     */
    public function testChallengePeriods()
    {
    }

    /**
     * Test case for challengeRead
     *
     * Get Challenge.
     *
     */
    public function testChallengeRead()
    {
    }

    /**
     * Test case for challengeRemoveMembers
     *
     * Remove members.
     *
     */
    public function testChallengeRemoveMembers()
    {
    }

    /**
     * Test case for challengeTeamList
     *
     * Team leaderboard.
     *
     */
    public function testChallengeTeamList()
    {
    }

    /**
     * Test case for challengeTeamRead
     *
     * Team contribution.
     *
     */
    public function testChallengeTeamRead()
    {
    }

    /**
     * Test case for challengeUpdate
     *
     * Edit challenge.
     *
     */
    public function testChallengeUpdate()
    {
    }
}
