<?php
/**
 * ProfileApiTest
 * PHP version 5
 *
 * @category Class
 * @package  WeFitter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * WeFitter API
 *
 * This is the WeFitter API
 *
 * OpenAPI spec version: v1.1
 * Contact: hello@wefitter.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace WeFitter\Client;

use WeFitter\Client\Configuration;
use WeFitter\Client\ApiException;
use WeFitter\Client\ObjectSerializer;

/**
 * ProfileApiTest Class Doc Comment
 *
 * @category Class
 * @package  WeFitter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProfileApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for profileActivitiesList
     *
     * DEPRECATED: Workout - Use /workout/ instead..
     *
     */
    public function testProfileActivitiesList()
    {
    }

    /**
     * Test case for profileActivityList
     *
     * DEPRECATED: Workout - Use /workout/ instead..
     *
     */
    public function testProfileActivityList()
    {
    }

    /**
     * Test case for profileActivitySegmentList
     *
     * Activity segment.
     *
     */
    public function testProfileActivitySegmentList()
    {
    }

    /**
     * Test case for profileBiometricList
     *
     * Bio Metric.
     *
     */
    public function testProfileBiometricList()
    {
    }

    /**
     * Test case for profileBiometricsList
     *
     * DEPRECATED: Bio Metric - Use /biometric/ instead..
     *
     */
    public function testProfileBiometricsList()
    {
    }

    /**
     * Test case for profileBmiList
     *
     * BMI.
     *
     */
    public function testProfileBmiList()
    {
    }

    /**
     * Test case for profileChallengeRead
     *
     * Challenge.
     *
     */
    public function testProfileChallengeRead()
    {
    }

    /**
     * Test case for profileChallenges
     *
     * Challenges.
     *
     */
    public function testProfileChallenges()
    {
    }

    /**
     * Test case for profileConnectionWidgetRead
     *
     * Connections Widget.
     *
     */
    public function testProfileConnectionWidgetRead()
    {
    }

    /**
     * Test case for profileConnectionsRead
     *
     * Connections.
     *
     */
    public function testProfileConnectionsRead()
    {
    }

    /**
     * Test case for profileCreate
     *
     * Create Profile.
     *
     */
    public function testProfileCreate()
    {
    }

    /**
     * Test case for profileDailySummariesList
     *
     * DEPRECATED: Daily Summary - Use /daily_summary/ instead..
     *
     */
    public function testProfileDailySummariesList()
    {
    }

    /**
     * Test case for profileDailySummaryList
     *
     * Daily Summary.
     *
     */
    public function testProfileDailySummaryList()
    {
    }

    /**
     * Test case for profileDailySummarySampleList
     *
     * Daily Summary Sample.
     *
     */
    public function testProfileDailySummarySampleList()
    {
    }

    /**
     * Test case for profileDelete
     *
     * Delete Profile.
     *
     */
    public function testProfileDelete()
    {
    }

    /**
     * Test case for profileEventCreate
     *
     * Create Event.
     *
     */
    public function testProfileEventCreate()
    {
    }

    /**
     * Test case for profileEventList
     *
     * Event.
     *
     */
    public function testProfileEventList()
    {
    }

    /**
     * Test case for profileHeartrateSummariesList
     *
     * DEPRECATED: Heart Rate Summary - Use /heartrate_summary/ instead..
     *
     */
    public function testProfileHeartrateSummariesList()
    {
    }

    /**
     * Test case for profileHeartrateSummaryList
     *
     * Heart Rate Summary.
     *
     */
    public function testProfileHeartrateSummaryList()
    {
    }

    /**
     * Test case for profileHeightList
     *
     * Height.
     *
     */
    public function testProfileHeightList()
    {
    }

    /**
     * Test case for profileList
     *
     * List Profiles.
     *
     */
    public function testProfileList()
    {
    }

    /**
     * Test case for profilePartialUpdate
     *
     * Partial Update.
     *
     */
    public function testProfilePartialUpdate()
    {
    }

    /**
     * Test case for profileRead
     *
     * Get Profile.
     *
     */
    public function testProfileRead()
    {
    }

    /**
     * Test case for profileRegisterPushNotificationsDelete
     *
     * Remove a push notification registration.
     *
     */
    public function testProfileRegisterPushNotificationsDelete()
    {
    }

    /**
     * Test case for profileRegisterPushNotificationsUpdate
     *
     * Add push notification registration.
     *
     */
    public function testProfileRegisterPushNotificationsUpdate()
    {
    }

    /**
     * Test case for profileSleepSummariesList
     *
     * DEPRECATED: Sleep Summary - Use /sleep_summary/ instead..
     *
     */
    public function testProfileSleepSummariesList()
    {
    }

    /**
     * Test case for profileSleepSummaryList
     *
     * Sleep Summary.
     *
     */
    public function testProfileSleepSummaryList()
    {
    }

    /**
     * Test case for profileStressSamplesList
     *
     * Stress Sample.
     *
     */
    public function testProfileStressSamplesList()
    {
    }

    /**
     * Test case for profileStressSummaryList
     *
     * Stress Summary.
     *
     */
    public function testProfileStressSummaryList()
    {
    }

    /**
     * Test case for profileUpdate
     *
     * Update profile.
     *
     */
    public function testProfileUpdate()
    {
    }

    /**
     * Test case for profileWeightList
     *
     * Weight.
     *
     */
    public function testProfileWeightList()
    {
    }

    /**
     * Test case for profileWorkoutList
     *
     * Workout.
     *
     */
    public function testProfileWorkoutList()
    {
    }
}
