<?php
/**
 * TeamApiTest
 * PHP version 5
 *
 * @category Class
 * @package  WeFitter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * WeFitter API
 *
 * This is the WeFitter API
 *
 * OpenAPI spec version: v1.1
 * Contact: hello@wefitter.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace WeFitter\Client;

use WeFitter\Client\Configuration;
use WeFitter\Client\ApiException;
use WeFitter\Client\ObjectSerializer;

/**
 * TeamApiTest Class Doc Comment
 *
 * @category Class
 * @package  WeFitter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TeamApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for teamCreate
     *
     * Create Team.
     *
     */
    public function testTeamCreate()
    {
    }

    /**
     * Test case for teamDelete
     *
     * Deletes a Team.
     *
     */
    public function testTeamDelete()
    {
    }

    /**
     * Test case for teamList
     *
     * List Teams.
     *
     */
    public function testTeamList()
    {
    }

    /**
     * Test case for teamMemberCreate
     *
     * Add member.
     *
     */
    public function testTeamMemberCreate()
    {
    }

    /**
     * Test case for teamMemberDelete
     *
     * Remove member.
     *
     */
    public function testTeamMemberDelete()
    {
    }

    /**
     * Test case for teamMemberUpdate
     *
     * Add member.
     *
     */
    public function testTeamMemberUpdate()
    {
    }

    /**
     * Test case for teamMembersCreate
     *
     * Add members.
     *
     */
    public function testTeamMembersCreate()
    {
    }

    /**
     * Test case for teamMembersUpdate
     *
     * Add members.
     *
     */
    public function testTeamMembersUpdate()
    {
    }

    /**
     * Test case for teamPartialUpdate
     *
     * Partial Edit a Team.
     *
     */
    public function testTeamPartialUpdate()
    {
    }

    /**
     * Test case for teamRead
     *
     * Team.
     *
     */
    public function testTeamRead()
    {
    }

    /**
     * Test case for teamRemoveMembers
     *
     * Remove members.
     *
     */
    public function testTeamRemoveMembers()
    {
    }

    /**
     * Test case for teamUpdate
     *
     * Edit Team.
     *
     */
    public function testTeamUpdate()
    {
    }
}
